[template.environment]
  GQL_HOST = "https://woo.adventureelevated.com/"
  NUXT_IMAGE_DOMAINS = "woo.adventureelevated.com"

[build]
  command = "nuxt generate"

[images]
  remote_images = ["https://woo.adventureelevated.com/.*"]
