query getCompositeProduct($id: ID!) {
  product(id: $id, idType: DATABASE_ID) {
    id
    ... on CompositeProduct {
      id
      databaseId
      name
      stockStatus
      averageRating
      reviewCount
      sku
      description
      shortDescription
      image {
        sourceUrl
      }
      galleryImages {
        nodes {
          sourceUrl
        }
      }
      productCategories {
        nodes {
          name
          slug
        }
      }
      components {
        id
        title
        description
        queryOptions {
          id
          databaseId
          type
          name
          attributes {
            nodes {
              id
              name
              label
            }
          }
          ... on VariableProduct {
            id
            name
            price(format: FORMATTED)
            regularPrice(format: FORMATTED)
            salePrice
            variations {
              nodes {
                id
                attributes {
                  nodes {
                    name
                    value
                  }
                }
                price(format: FORMATTED)
                salePrice(format: FORMATTED)
                regularPrice(format: FORMATTED)
                sku
                stockQuantity
                stockStatus
                featuredImage {
                  node {
                    sourceUrl
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
